
import __ASTRO_IMAGE_IMPORT_rdEdO from "/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdavid-lee.md";
import __ASTRO_IMAGE_IMPORT_BIIY9 from "/src/images/team/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Femma-carter.md";
import __ASTRO_IMAGE_IMPORT_92tHQ from "/src/images/team/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fisaac-turner.md";
import __ASTRO_IMAGE_IMPORT_Z1OgrDk from "/src/images/team/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjordan-wells.md";
import __ASTRO_IMAGE_IMPORT_Z1vogE4 from "/src/images/team/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjuliet-ramos.md";
import __ASTRO_IMAGE_IMPORT_Z2554tD from "/src/images/courses/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcourses%2Fastro-content-collections.md";
import __ASTRO_IMAGE_IMPORT_1QgtiU from "/src/images/courses/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcourses%2Fastro-fundamentals.md";
import __ASTRO_IMAGE_IMPORT_2vMhxm from "/src/images/teachers/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fastrid-nyberg.md";
import __ASTRO_IMAGE_IMPORT_ZJ29fb from "/src/images/teachers/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Ffreja-lindholm.md";
import __ASTRO_IMAGE_IMPORT_1UaLni from "/src/images/teachers/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Flucia-herrera.md";
import __ASTRO_IMAGE_IMPORT_Z28zzk8 from "/src/images/teachers/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fmatteo-romano.md";
import __ASTRO_IMAGE_IMPORT_LLAaz from "/src/images/teachers/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fnils-vestergaard.md";
import __ASTRO_IMAGE_IMPORT_ZhdBRq from "/src/images/teachers/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fsoren-dahl.md";
import __ASTRO_IMAGE_IMPORT_1jNB93 from "/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffood-packaging-customer-service-numbers-decline.md";
import __ASTRO_IMAGE_IMPORT_Z1lA5Pe from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-feedback-food-packaging.md";
import __ASTRO_IMAGE_IMPORT_2oAc5k from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-alternative-fabform-99-dollar-one-time.md";
export default new Map([["/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdavid-lee.md", __ASTRO_IMAGE_IMPORT_rdEdO], ["/src/images/team/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Femma-carter.md", __ASTRO_IMAGE_IMPORT_BIIY9], ["/src/images/team/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fisaac-turner.md", __ASTRO_IMAGE_IMPORT_92tHQ], ["/src/images/team/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjordan-wells.md", __ASTRO_IMAGE_IMPORT_Z1OgrDk], ["/src/images/team/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjuliet-ramos.md", __ASTRO_IMAGE_IMPORT_Z1vogE4], ["/src/images/courses/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcourses%2Fastro-content-collections.md", __ASTRO_IMAGE_IMPORT_Z2554tD], ["/src/images/courses/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcourses%2Fastro-fundamentals.md", __ASTRO_IMAGE_IMPORT_1QgtiU], ["/src/images/teachers/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fastrid-nyberg.md", __ASTRO_IMAGE_IMPORT_2vMhxm], ["/src/images/teachers/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Ffreja-lindholm.md", __ASTRO_IMAGE_IMPORT_ZJ29fb], ["/src/images/teachers/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Flucia-herrera.md", __ASTRO_IMAGE_IMPORT_1UaLni], ["/src/images/teachers/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fmatteo-romano.md", __ASTRO_IMAGE_IMPORT_Z28zzk8], ["/src/images/teachers/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fnils-vestergaard.md", __ASTRO_IMAGE_IMPORT_LLAaz], ["/src/images/teachers/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteachers%2Fsoren-dahl.md", __ASTRO_IMAGE_IMPORT_ZhdBRq], ["/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffood-packaging-customer-service-numbers-decline.md", __ASTRO_IMAGE_IMPORT_1jNB93], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-feedback-food-packaging.md", __ASTRO_IMAGE_IMPORT_Z1lA5Pe], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-alternative-fabform-99-dollar-one-time.md", __ASTRO_IMAGE_IMPORT_2oAc5k]]);
		