
import __ASTRO_IMAGE_IMPORT_Z12zaPC from "/src/images/blog/creative-ways-to-use-qr-code-feedback-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FHigh-Impact-Ways-to-Use-QR-Code-Feedback-Forms.md";
import __ASTRO_IMAGE_IMPORT_1CVxDv from "/src/images/blog/cheaper-alternative-typeform.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcheaper-alternative-to-typeform.md";
import __ASTRO_IMAGE_IMPORT_Z1BT8Dn from "/src/images/blog/creative-ways-to-use-qr-code-feedback-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcreative-ways-to-use-qr-code-feedback-forms.md";
import __ASTRO_IMAGE_IMPORT_26cLOa from "/src/images/blog/degoogle-google-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdegoogle-google-forms-fabform.md";
import __ASTRO_IMAGE_IMPORT_1jNB93 from "/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffood-packaging-customer-service-numbers-decline.md";
import __ASTRO_IMAGE_IMPORT_1Vr2gq from "/src/images/blog/feedback.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fhow-to-get-more-feedback-with-qr-codes.md";
import __ASTRO_IMAGE_IMPORT_fqElr from "/src/images/blog/qr-code-coffee-shop-feedback.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-feedback-coffee-shop.md";
import __ASTRO_IMAGE_IMPORT_Z1lA5Pe from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-feedback-food-packaging.md";
import __ASTRO_IMAGE_IMPORT_1o9yc9 from "/src/images/blog/qr-code-payment-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-payment-forms.md";
import __ASTRO_IMAGE_IMPORT_Z1Q1tV7 from "/src/images/blog/qr-code-receipt-feedback.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-receipt-feedback.md";
import __ASTRO_IMAGE_IMPORT_2oAc5k from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-alternative-fabform-99-dollar-one-time.md";
import __ASTRO_IMAGE_IMPORT_1i6rdn from "/src/images/blog/typeform-is-too-expensive.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-pricing-alternative.md";
import __ASTRO_IMAGE_IMPORT_lJ7ED from "/src/images/blog/typeform-is-too-expensive.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-too-expensive.md";
import __ASTRO_IMAGE_IMPORT_ZRDmnH from "/src/images/blog/feedback-form-tutorial-tablet-survey.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fwrite-effective-feedback-forms-fabform-tutorial.md";
import __ASTRO_IMAGE_IMPORT_Z1waii8 from "/src/images/blog/google-forms-redirect-problem-fabform.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgoogle-forms-redirect-problem-fabform.md";
export default new Map([["/src/images/blog/creative-ways-to-use-qr-code-feedback-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FHigh-Impact-Ways-to-Use-QR-Code-Feedback-Forms.md", __ASTRO_IMAGE_IMPORT_Z12zaPC], ["/src/images/blog/cheaper-alternative-typeform.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcheaper-alternative-to-typeform.md", __ASTRO_IMAGE_IMPORT_1CVxDv], ["/src/images/blog/creative-ways-to-use-qr-code-feedback-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcreative-ways-to-use-qr-code-feedback-forms.md", __ASTRO_IMAGE_IMPORT_Z1BT8Dn], ["/src/images/blog/degoogle-google-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdegoogle-google-forms-fabform.md", __ASTRO_IMAGE_IMPORT_26cLOa], ["/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffood-packaging-customer-service-numbers-decline.md", __ASTRO_IMAGE_IMPORT_1jNB93], ["/src/images/blog/feedback.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fhow-to-get-more-feedback-with-qr-codes.md", __ASTRO_IMAGE_IMPORT_1Vr2gq], ["/src/images/blog/qr-code-coffee-shop-feedback.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-feedback-coffee-shop.md", __ASTRO_IMAGE_IMPORT_fqElr], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-feedback-food-packaging.md", __ASTRO_IMAGE_IMPORT_Z1lA5Pe], ["/src/images/blog/qr-code-payment-forms.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-payment-forms.md", __ASTRO_IMAGE_IMPORT_1o9yc9], ["/src/images/blog/qr-code-receipt-feedback.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fqr-code-receipt-feedback.md", __ASTRO_IMAGE_IMPORT_Z1Q1tV7], ["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-alternative-fabform-99-dollar-one-time.md", __ASTRO_IMAGE_IMPORT_2oAc5k], ["/src/images/blog/typeform-is-too-expensive.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-pricing-alternative.md", __ASTRO_IMAGE_IMPORT_1i6rdn], ["/src/images/blog/typeform-is-too-expensive.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ftypeform-too-expensive.md", __ASTRO_IMAGE_IMPORT_lJ7ED], ["/src/images/blog/feedback-form-tutorial-tablet-survey.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fwrite-effective-feedback-forms-fabform-tutorial.md", __ASTRO_IMAGE_IMPORT_ZRDmnH], ["/src/images/blog/google-forms-redirect-problem-fabform.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgoogle-forms-redirect-problem-fabform.md", __ASTRO_IMAGE_IMPORT_Z1waii8]]);
		